//! Opt-in real-host acceptance coverage for the bounded M3 I/O scenario.
//! This test is deliberately ignored because it writes only beneath an owned
//! directory in the checkout and can create real block-I/O pressure.

use std::fs;
use std::io::{self, Read};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Output, Stdio};
use std::sync::{
    Mutex,
    atomic::{AtomicU64, Ordering},
};
use std::thread;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

const WORKER_COUNT: usize = 2;
const BYTES_PER_WORKER: u64 = 64 * 1024 * 1024;
const REQUIRED_FREE_BYTES: u64 = (WORKER_COUNT as u64 + 1) * BYTES_PER_WORKER;
const STRESS_TIMEOUT_SECS: u64 = 8;
const HUNT_TIMEOUT: Duration = Duration::from_secs(5);
static ACCEPTANCE_LOCK: Mutex<()> = Mutex::new(());
static UNIQUE_DIRECTORY_COUNTER: AtomicU64 = AtomicU64::new(0);

/// An owned directory directly below the manifest directory.  In this test
/// environment that is block-backed; `/tmp` may instead be tmpfs and would
/// make an I/O-PSI experiment meaningless.
struct OwnedTempDir {
    path: PathBuf,
}

impl OwnedTempDir {
    fn create() -> io::Result<Self> {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        for _ in 0..32 {
            let sequence = UNIQUE_DIRECTORY_COUNTER.fetch_add(1, Ordering::Relaxed);
            let path = root.join(format!(
                ".io-acceptance-{}-{timestamp}-{sequence}",
                std::process::id()
            ));
            match fs::create_dir(&path) {
                Ok(()) => return Ok(Self { path }),
                Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
                Err(error) => return Err(error),
            }
        }
        Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            "could not allocate a unique I/O acceptance directory",
        ))
    }
}

impl Drop for OwnedTempDir {
    fn drop(&mut self) {
        // The directory name is generated by this test and is never shared.
        let _ = fs::remove_dir_all(&self.path);
    }
}

struct StressCleanup {
    child: Child,
}

impl StressCleanup {
    fn still_running(&mut self) -> io::Result<bool> {
        Ok(self.child.try_wait()?.is_none())
    }
}

impl Drop for StressCleanup {
    fn drop(&mut self) {
        match self.child.try_wait() {
            Ok(Some(_)) => {}
            Ok(None) | Err(_) => {
                let _ = self.child.kill();
                let _ = self.child.wait();
            }
        }
    }
}

fn free_bytes(path: &Path) -> io::Result<u64> {
    // `df -Pk` is part of the Linux precondition for this test.  It avoids a
    // new dependency solely for statvfs and reports POSIX 1 KiB blocks.
    let output = Command::new("df")
        .args(["-Pk", path.to_string_lossy().as_ref()])
        .output()?;
    if !output.status.success() {
        return Err(io::Error::other(
            "df could not inspect the acceptance directory",
        ));
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    let fields = stdout
        .lines()
        .last()
        .ok_or_else(|| io::Error::other("df returned no filesystem row"))?
        .split_whitespace()
        .collect::<Vec<_>>();
    let available_kib = fields
        .get(3)
        .ok_or_else(|| io::Error::other("df output lacked available blocks"))?
        .parse::<u64>()
        .map_err(|_| io::Error::other("df available blocks were not numeric"))?;
    available_kib
        .checked_mul(1024)
        .ok_or_else(|| io::Error::other("df available-byte calculation overflowed"))
}

fn stress_ng_supports_hdd_options(temp_path: &Path) -> bool {
    let help = match Command::new("stress-ng").arg("--help").output() {
        Ok(output) if output.status.success() => output,
        Ok(output) => {
            eprintln!(
                "skipping I/O acceptance: stress-ng --help exited {}",
                output.status
            );
            return false;
        }
        Err(error) if error.kind() == io::ErrorKind::NotFound => {
            eprintln!("skipping I/O acceptance: stress-ng is not installed");
            return false;
        }
        Err(error) => {
            eprintln!("skipping I/O acceptance: cannot invoke stress-ng: {error}");
            return false;
        }
    };
    let help = String::from_utf8_lossy(&help.stdout);
    if !(help.contains("--dry-run")
        && help.contains("--hdd ")
        && help.contains("--hdd-bytes")
        && help.contains("--hdd-opts")
        && help.contains("--temp-path"))
    {
        eprintln!("skipping I/O acceptance: stress-ng lacks required hdd options");
        return false;
    }

    // `--hdd 0` means one worker per online CPU, not zero workers.  Validate
    // the exact bounded command in stress-ng's non-executing dry-run mode.
    let worker_count = WORKER_COUNT.to_string();
    let worker_bytes = BYTES_PER_WORKER.to_string();
    match Command::new("stress-ng")
        .args(["--dry-run", "--hdd", &worker_count])
        .args(["--hdd-bytes", &worker_bytes])
        .args(["--hdd-opts", "direct,sync,fsync"])
        .arg("--temp-path")
        .arg(temp_path)
        .args(["--timeout", "1"])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
    {
        Ok(status) if status.success() => true,
        Ok(status) => {
            eprintln!(
                "skipping I/O acceptance: stress-ng does not accept direct,sync,fsync ({status})"
            );
            false
        }
        Err(error) => {
            eprintln!("skipping I/O acceptance: cannot validate stress-ng hdd options: {error}");
            false
        }
    }
}

fn run_with_timeout(mut command: Command, timeout: Duration) -> io::Result<Output> {
    command.stdout(Stdio::piped()).stderr(Stdio::piped());
    let mut child = command.spawn()?;
    let stdout = child.stdout.take().expect("stdout pipe should be present");
    let stderr = child.stderr.take().expect("stderr pipe should be present");
    let stdout_reader = thread::spawn(move || -> io::Result<Vec<u8>> {
        let mut bytes = Vec::new();
        let mut stdout = stdout;
        stdout.read_to_end(&mut bytes)?;
        Ok(bytes)
    });
    let stderr_reader = thread::spawn(move || -> io::Result<Vec<u8>> {
        let mut bytes = Vec::new();
        let mut stderr = stderr;
        stderr.read_to_end(&mut bytes)?;
        Ok(bytes)
    });
    let deadline = Instant::now() + timeout;
    let (status, timed_out) = loop {
        if let Some(status) = child.try_wait()? {
            break (status, false);
        }
        if Instant::now() >= deadline {
            let _ = child.kill();
            break (child.wait()?, true);
        }
        thread::sleep(Duration::from_millis(20));
    };
    let stdout = stdout_reader
        .join()
        .map_err(|_| io::Error::other("stdout reader thread panicked"))??;
    let stderr = stderr_reader
        .join()
        .map_err(|_| io::Error::other("stderr reader thread panicked"))??;
    if timed_out {
        return Err(io::Error::new(
            io::ErrorKind::TimedOut,
            "stallhunt hunt exceeded the acceptance-test timeout",
        ));
    }
    Ok(Output {
        status,
        stdout,
        stderr,
    })
}

#[test]
#[ignore = "creates bounded block-I/O pressure; run with cargo test --test io_acceptance -- --ignored"]
fn bounded_real_io_pressure_reports_activity_candidates() {
    let _acceptance_guard = ACCEPTANCE_LOCK
        .lock()
        .expect("acceptance-test serialization lock should not be poisoned");
    if !cfg!(target_os = "linux") {
        eprintln!("skipping I/O acceptance: Linux is required");
        return;
    }
    if fs::read_to_string("/proc/pressure/io").is_err() {
        eprintln!("skipping I/O acceptance: I/O PSI is unavailable or unreadable");
        return;
    }
    let temp = match OwnedTempDir::create() {
        Ok(temp) => temp,
        Err(error) => {
            eprintln!("skipping I/O acceptance: cannot create owned directory: {error}");
            return;
        }
    };
    match free_bytes(&temp.path) {
        Ok(bytes) if bytes > REQUIRED_FREE_BYTES => {}
        Ok(bytes) => {
            eprintln!(
                "skipping I/O acceptance: only {bytes} free bytes, need more than {REQUIRED_FREE_BYTES}"
            );
            return;
        }
        Err(error) => {
            eprintln!("skipping I/O acceptance: cannot verify free space: {error}");
            return;
        }
    }
    if !stress_ng_supports_hdd_options(&temp.path) {
        return;
    }

    let stress_timeout = STRESS_TIMEOUT_SECS.to_string();
    let child = match Command::new("stress-ng")
        .args([
            "--hdd",
            "2",
            "--hdd-bytes",
            "64M",
            "--hdd-opts",
            "direct,sync,fsync",
            "--temp-path",
            temp.path.to_string_lossy().as_ref(),
            "--timeout",
            &stress_timeout,
        ])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
    {
        Ok(child) => child,
        Err(error) => {
            eprintln!("skipping I/O acceptance: cannot start stress-ng: {error}");
            return;
        }
    };
    // Declare the guard after the directory so it is killed and reaped before
    // the directory's exact cleanup on every return or assertion failure.
    let mut stress = StressCleanup { child };
    thread::sleep(Duration::from_millis(250));
    match stress.still_running() {
        Ok(true) => {}
        Ok(false) => {
            eprintln!(
                "skipping I/O acceptance: stress-ng exited before sampling (unsupported runtime option or launch limit)"
            );
            return;
        }
        Err(error) => {
            eprintln!("skipping I/O acceptance: cannot inspect stress-ng: {error}");
            return;
        }
    }

    let mut command = Command::new(env!("CARGO_BIN_EXE_stallhunt"));
    command.args(["hunt", "--duration", "2s", "--json"]);
    let output = run_with_timeout(command, HUNT_TIMEOUT)
        .expect("the bounded I/O JSON hunt should complete before its timeout");
    assert!(
        stress
            .still_running()
            .expect("stress-ng liveness should remain observable"),
        "stress-ng exited during the bounded observation window"
    );
    assert!(
        output.status.success(),
        "hunt failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let json: serde_json::Value = serde_json::from_slice(&output.stdout)
        .expect("hunt JSON should parse during synthetic I/O pressure");
    if json["capabilities"]["io_psi"]["state"].as_str() != Some("available")
        || json["capabilities"]["diskstats"] != "available"
        || json["capabilities"]["process_io"] != "available"
    {
        eprintln!("skipping I/O acceptance: required I/O telemetry became unavailable: {json}");
        return;
    }

    let finding = json["findings"].as_array().and_then(|findings| {
        findings
            .iter()
            .find(|finding| finding["kind"] == "io_pressure")
    });
    let Some(finding) = finding else {
        panic!("bounded real I/O pressure must report an io_pressure finding: {json}");
    };
    assert!(
        finding["device_candidates"]
            .as_array()
            .is_some_and(|candidates| !candidates.is_empty()),
        "I/O pressure with complete diskstats must include same-window device activity candidates: {json}"
    );
    assert!(
        finding["process_suspects"]
            .as_array()
            .is_some_and(|suspects| !suspects.is_empty()),
        "I/O pressure with complete process I/O must include same-window process activity suspects: {json}"
    );
    eprintln!(
        "I/O acceptance: psi_some_fraction={} psi_window_us={} diskstats_window_us={} process_io_window_us={} device_candidates={} process_suspects={}",
        finding["evidence"]["psi_some_fraction"],
        finding["evidence"]["psi_window_us"],
        finding["evidence"]["diskstats_window_us"],
        finding["evidence"]["process_io_window_us"],
        finding["device_candidates"].as_array().map_or(0, Vec::len),
        finding["process_suspects"].as_array().map_or(0, Vec::len),
    );
}
